spring:
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

  liquibase:
    change-log: db/db.changelog-main.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME} # 데이터베이스 커넥션 이름
    password: ${DB_PASSWORD} # 데이터베이스 커넥션 비밀번호
    url: ${DB_URL}

server:
  port: 8080